# src/Ens/JobeetBundle/Resources/config/validation.yml
Ens\JoobetBundle\Entity\Job:
    properties:
      email:
        - NotBlank: ~
        - Email: ~
      type:
        - NotBlank: ~
        - Choice: { callback: getTypeValues }
      company:
        - NotBlank: ~
      position:
        - NotBlank: ~
      location:
        - NotBlank: ~
      description:
        - NotBlank: ~
      how_to_apply:
        - NotBlank: ~
      category:
        - NotBlank: ~
      file:
        - Image: ~
