ens_job:
    pattern:  /
    defaults: { _controller: "EnsJoobetBundle:Job:index" }

ens_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsJoobetBundle:Job:show" }
    requirements:
      id: \d+

ens_job_new:
    pattern:  /new
    defaults: { _controller: "EnsJoobetBundle:Job:new" }

ens_job_create:
    pattern:  /create
    defaults: { _controller: "EnsJoobetBundle:Job:create" }
    requirements: { _method: post }

ens_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "EnsJoobetBundle:Job:edit" }

ens_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "EnsJoobetBundle:Job:update" }
    requirements: { _method: post }

ens_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "EnsJoobetBundle:Job:delete" }
    requirements: { _method: post }
